### ISSUE TITLE
Can not login. If not use debug 

### ISSUE THREAD

**Issue by Zifai** [Iakobs/godot-play-game-services#3]
I tried testing in the Play Store, I always couldn't log in, 
if I tried directly in Godot, I had to fill in the debug key and release key before I could log in. If I just used release key couldn't log in.

**Comment by Zifai** [comment]
I just filled in the debug keystore and was able to log in

**Comment by Iakobs** [comment]
Hi @Zifai 

sorry for the late reply, I've been off for a couple of days to the holidays season. I understand you were finally able to login properly?

I yet have to test releasing an actual app with a release keystore to sign the app, etc. But with the debug keystore it has been working fine for me. You have to do a lot of configuration in the Google Play Console and the Google Cloud to test this, which I understand you already have done.

I'ts true also that the signing in workflow for play games works a bit strange sometimes, I think there's a delay between setting things up in Google Play Console and being able to actually log in. Whenever I have to log in from a new device, for example, I also have some problems that solve on their own just by waiting a little bit of time.

According to Google Play Games documentation, you don't need to install the Play Games app and sign in there, but I'm not sure if that's completely true. In the demo project, in the MainMenu.gd script, you will see how I log in.

Summarising, I call the `initialize` method of the plugin and subscribe to the `userAuthenticated` signal. If the response of the signal is false, then I call the `signIn` method of the plugin.

**Comment by Zifai** [comment]
@Iakobs  

I still can't login if it releases on play store.

If I just Write  debug keystore I can login only install  direct from godot 

But play store Only accepts apps with keystore release

**Comment by Iakobs** [comment]
I'm working with another dev to publish a game to the play store and we will be able to test all of this. I'm sorry I can't help you more for now with this issue :(

I will leave this issue open and get back to you as soon as I have something new. Thanks for your interest in the plugin!

**Comment by Iakobs** [comment]
Good morning @Zifai 

I've been able to generate a release version of a game, using the release keystore to sign it and log in, and it's working for me, without the debug keystore.

Have you configured the OAuth2 clients in your Google Cloud and linked them in your app's Play Games section?

Also, are you able to trace the problem? Meaning, are you able to see in the logs of your app what's happening exactly? using the `com.google.android.gms` package in your logcat filter in Android Studio is very helpful, since you can see all Google logs there (there are also unrelated logs, don't get confused by them).

Please, let me know if any of these help!

**Comment by Zifai** [comment]
@Iakobs 

Thanks , I don"t know android studio magic loggcat hahahaha .

after I found out it turned out
SHA-1 certificate fingerprint, different from all SHA-1 certificate fingerprint that I have.

very strange
